version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./config.yaml:/app/config.yaml
    environment:
      - CONFIG_PATH=/app/config.yaml
    command: ./run.sh
    tty: false
